services:
  db:
    image: postgres
    container_name: soccer_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d:ro
      - pg_data:/var/lib/postgresql/data

  selenium:
    image: seleniarm/standalone-chromium:latest
    container_name: selenium
    restart: always
    ports:
      - "4444:4444"
    shm_size: 2g
  
  backend:
    container_name: backend
    build: ./backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
  
  frontend:
    container_name: frontend
    build: ./frontend/soccer-webpage
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
      
  scraper:
    container_name: scraper
    build: ./scraper
    depends_on:
      - db
      - selenium
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    command: ["python", "scraper.py"]
volumes:
  pg_data:
